version: '3'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        restart: unless-stopped
        volumes: 
            - /app/node_modules
            - ./:/app
        ports: 
            - '3000:3000'